(load  (concat (file-name-directory load-file-name) "bootstrap.el"))
(set-face-attribute 'default nil :font "Fira Code" :height 110)

(when (eq system-type 'darwin)
  (set-face-attribute 'default nil :font "Fira Code" :height 150)
  (setq mac-command-modifier 'meta)
  ;; (setq mac-option-modifier 'meta)
  (setq mac-right-option-modifier nil)
  (setq ns-auto-hide-menu-bar t)
  (setq ring-bell-function 'ignore)
  (use-package exec-path-from-shell
    :ensure t)
  (when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
  (set-frame-parameter (selected-frame) 'alpha '(90 90))
  (add-to-list 'default-frame-alist '(alpha 90 90))
  )

;; desktop save mode
(setq desktop-path '("."))
(if (file-exists-p ".emacs.desktop")
    (desktop-save-mode 1))


(load  (concat (file-name-directory load-file-name) "functions.el"))
(load  (concat (file-name-directory load-file-name) "commands/init.el"))
(load  (concat (file-name-directory load-file-name) "editor.el"))
(load  (concat (file-name-directory load-file-name) "ui.el"))
(load  (concat (file-name-directory load-file-name) "vcs.el"))
(load  (concat (file-name-directory load-file-name) "lang/init.el"))
(load  (concat (file-name-directory load-file-name) "leader.el"))
(load  (concat (file-name-directory load-file-name) "spelling.el"))
(load  (concat (file-name-directory load-file-name) "font-ligatures.el"))
(load  (concat (file-name-directory load-file-name) "themes/savoy-truffle-theme.el"))
(load-theme 'savoy-truffle)
;; (load  (concat (file-name-directory load-file-name) "vendor/vimgolf.el"))
(load  (concat (file-name-directory load-file-name) "apps.el"))
